import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "BYOW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header /> 
        <main className="container mx-auto px-6 py-8">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
