import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import BackgroundContent from "./components/BackgroundContent";

export const metadata: Metadata = {
  title: "BYOW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-G3VDZC765B"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-G3VDZC765B');
          `}
        </Script>
      </head>
      <body className="antialiased relative w-full h-full min-h-screen">
        {/* Video section - fixed height for hero area */}
        <div className="fixed top-0 left-0 w-full h-screen z-0 overflow-hidden">
          <video
            className="w-full h-full object-cover"
            autoPlay
            loop
            muted
            playsInline
          >
            <source src="/videos/Background Video.mp4" type="video/mp4" />
          </video>
          {/* Gradient overlay for smooth transition */}
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-[#040010]" />
        </div>

        {/* Solid color section - starts after hero */}
        <div className="absolute top-[100vh] left-0 w-full min-h-screen bg-[#040010] z-0"></div>

        {/* Content wrapper that sits on top of both backgrounds */}
        <div className="relative z-10 w-full min-h-screen">
          <BackgroundContent>{children}</BackgroundContent>
        </div>
      </body>
    </html>
  );
}
